FROM registry.hub.docker.com/library/almalinux:9

RUN dnf update -y
RUN dnf install -y https://repository.egi.eu/sw/production/umd/5/al9/release/x86_64/umd-release-5.0.0-1.al9.alma.noarch.rpm
RUN dnf install -y python3-dirq python3-argo-ams-library apel-ssm-3.4.1
RUN dnf clean all
